/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcpProjectViews;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import static lcpProjectViews.Global_Chat.model;
import static lcpProjectViews.Global_Chat.user_list;

/**
 *
 * @author Berkay
 */
public class Club_Chat extends javax.swing.JFrame {

    Socket sock;
    PrintWriter writer;
    BufferedReader reader;
    ArrayList<String> users = new ArrayList<>();
    DefaultListModel<String> model;
    String ip_adress = SocketManager.IP_ADRESS;
    int portNumber = SocketManager.PORT_CLUB;
    /**
     * Creates new form Global_Chat
     */
    
    
    
    public Club_Chat() {
        initComponents();
        forOmer();
        initialized();
    }
    
    public  void initialized(){
        setResizable(false);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        txt_area.setEditable(false);
    }

    public void forOmer(){
        try {
                    sock = new Socket(ip_adress, portNumber);
                    InputStreamReader streamReader = new InputStreamReader(sock.getInputStream());
                    reader = new BufferedReader(streamReader);
                    writer = new PrintWriter(sock.getOutputStream());
                    String temp = User.LoggedUSER.getUserName() + ":" + "has connected." + ":" + "Connect";
                    writer.println(temp);
                    writer.flush();
                } catch (Exception e) {
                    System.err.println("Cannot Connect...");
                }
        ListenThread();
    }
    
    public class IncomingReader implements Runnable
    {
        @Override
        public void run() 
        {
            String[] data;
            String stream;

            try 
            {
                while (!(stream = reader.readLine()).equals("")) 
                {
                     data = stream.split(":");
                     System.err.println(stream);
                     
                     
                     
                      if (data[2].equals("Chat")) 
                     {
                        txt_area.append(data[0] + ": " + data[1] + "\n");
                        txt_area.setCaretPosition(txt_area.getDocument().getLength());
                     } 
                     else if (data[2].equals("Connect"))
                     {
                        txt_area.removeAll();
                        addUser(data[0]);
                         System.err.println("connecte girdi");
                     } 
                     else if (data[2].equals("Disconnect")) 
                     {
                         removeUser(data[0]);
                     } 
                     else if (data[2].equals("Done")) 
                     {
                        writeUser();
                        users.clear();
                     }
                     else{
                          System.err.println("bakalım");
                     }                     
                }
           }catch(Exception e) {
               e.printStackTrace();
           }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        center_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        txt_msg = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        west_panel = new javax.swing.JPanel();
        btn_announ = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane2.setViewportView(txt_area);

        txt_msg.setText("your message...");
        txt_msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_msgMouseClicked(evt);
            }
        });
        txt_msg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_msgKeyPressed(evt);
            }
        });

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout center_panelLayout = new javax.swing.GroupLayout(center_panel);
        center_panel.setLayout(center_panelLayout);
        center_panelLayout.setHorizontalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2)
                    .addGroup(center_panelLayout.createSequentialGroup()
                        .addComponent(txt_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        center_panelLayout.setVerticalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(center_panel, java.awt.BorderLayout.CENTER);

        btn_announ.setText("Announcements");
        btn_announ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_announMouseClicked(evt);
            }
        });

        jToolBar2.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lcpProjectViews/Logos/direction.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jScrollPane1.setViewportView(user_list);

        javax.swing.GroupLayout west_panelLayout = new javax.swing.GroupLayout(west_panel);
        west_panel.setLayout(west_panelLayout);
        west_panelLayout.setHorizontalGroup(
            west_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(west_panelLayout.createSequentialGroup()
                .addGroup(west_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btn_announ, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(west_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        west_panelLayout.setVerticalGroup(
            west_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, west_panelLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_announ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(west_panel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_msgMouseClicked
        txt_msg.setText(null);
    }//GEN-LAST:event_txt_msgMouseClicked

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
    String nothing = "";
        if((txt_msg.getText()).equals(nothing)){
            txt_msg.setText("");
            txt_msg.requestFocus();
        }
        else{
            try {
                writer.println(User.LoggedUSER.getUserName() + ":" + txt_msg.getText() + ":" + "Chat");
                writer.flush();
            } catch (Exception e) {
                e.printStackTrace();
                txt_area.append("Message was not sent !!\n");
            }
            txt_msg.setText(nothing);
            txt_msg.requestFocus();
        }
        txt_msg.setText(nothing);
            txt_msg.requestFocus();
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_announMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announMouseClicked
        //setVisible(true);
        if(User.LoggedUSER.isPresident()){
            ClubPresidentAnnouncements clubPresident = new ClubPresidentAnnouncements();
            clubPresident.setVisible(true);
        }else{
            Club_Chat_Announcements clubAnnouncement = new Club_Chat_Announcements();
            clubAnnouncement.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_announMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        disconnectedSend();
        Disconnect();
        dispose();
        Chat_Selection chatselect = new Chat_Selection();
        chatselect.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_msgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_msgKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            String nothing = "";
        if((txt_msg.getText()).equals(nothing)){
            txt_msg.setText("");
            txt_msg.requestFocus();
        }
        else{
            try {
                writer.println(User.LoggedUSER.getUserName() + ":" + txt_msg.getText() + ":" + "Chat");
                writer.flush();
            } catch (Exception e) {
                e.printStackTrace();
                txt_area.append("Message was not sent !!\n");
            }
            txt_msg.setText(nothing);
            txt_msg.requestFocus();
        }
        txt_msg.setText(nothing);
            txt_msg.requestFocus();
        }
    }//GEN-LAST:event_txt_msgKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Club_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Club_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Club_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Club_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Club_Chat().setVisible(true);
            }
        });
    }
    
    public void ListenThread(){
        Thread IncomingReader = new Thread(new Club_Chat.IncomingReader());
        IncomingReader.start();
    }
    
    public void addUser(String data){
        users.add(data);
    }
    
    public void removeUser(String data){
        txt_area.append(data + " is disconnected");
    }
    
    public void writeUser(){
        model = new DefaultListModel<>();
        user_list.setModel(model);
        for(String member : users){
            model.addElement(member);
        }       
    }
    
    public void disconnectedSend(){
        String dc = (User.LoggedUSER.getUserName() + ": :Disconnect");
        try {
            writer.println(dc);
            writer.flush();
        } catch (Exception e) {
            txt_area.append("Cannot send messages...");
        }
    }
    
    public void Disconnect(){
        try {
            txt_area.append("Disconnected\n");
            sock.close();
        } catch (Exception e) {
            txt_area.append("Cannot Disconnect");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_announ;
    private javax.swing.JButton btn_send;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_msg;
    private javax.swing.JList<String> user_list;
    private javax.swing.JPanel west_panel;
    // End of variables declaration//GEN-END:variables
}
