/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcpProjectViews;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Clock;
import javax.swing.JOptionPane;

/**
 *
 * @author OmerCeylan
 */
public class LoginPage extends javax.swing.JFrame {

    static final String DB_URL = DBManager.DB_URL;
    static final String USER = DBManager.DB_USER;
    static final String PASSWORD = DBManager.DB_PASS;
    
    
    public LoginPage() {
        initComponents();
        initialized();
    }
    
    public  void initialized(){
        setResizable(false);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        TFieldName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        TFieldPassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        BtnLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblCreateNewAccount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setLayout(new java.awt.GridLayout(5, 0));

        TFieldName.setText("User Name");
        TFieldName.setName("textFieldUserName"); // NOI18N
        TFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFieldNameFocusGained(evt);
            }
        });
        TFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFieldNameMouseClicked(evt);
            }
        });
        jPanel5.add(TFieldName);
        jPanel5.add(jPanel6);

        TFieldPassword.setText("jPasswordField1");
        TFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFieldPasswordFocusGained(evt);
            }
        });
        jPanel5.add(TFieldPassword);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7);

        BtnLogin.setText("Log In");
        BtnLogin.setName("btnLogin"); // NOI18N
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        jPanel5.add(BtnLogin);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lcpProjectViews/Logos/LeoLogo_omegas_bw100x108.gif"))); // NOI18N
        jPanel9.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        lblCreateNewAccount.setForeground(new java.awt.Color(0, 102, 204));
        lblCreateNewAccount.setText("Create New Account!");
        lblCreateNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateNewAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblCreateNewAccount)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblCreateNewAccount)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel11);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFieldNameMouseClicked
        TFieldName.setText("");
    }//GEN-LAST:event_TFieldNameMouseClicked

    private void TFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFieldNameFocusGained
        TFieldName.setText("");
    }//GEN-LAST:event_TFieldNameFocusGained

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        User user = new User();
        
        if(!TFieldName.getText().equals(null) && !TFieldPassword.getText().equals(null)){
            user.setUserName(TFieldName.getText());
            System.out.println("Name: " + user.getUserName());
            user.setPassword(TFieldPassword.getText());
            System.out.println("Password: " + user.getPassword());
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                Connection conn = (Connection) DriverManager.getConnection(DB_URL, USER, PASSWORD);
                
                System.out.println("Connected");
                
                Statement st = (Statement) conn.createStatement();
                
                String sql = "SELECT * FROM user WHERE username = '" + TFieldName.getText() + "'";
                
                ResultSet result = st.executeQuery(sql);
                
                System.out.println("Result Received");
                User receivedUser = new User();
                while (result.next()) {
                    receivedUser.setUserName(result.getString("username"));
                    receivedUser.setPassword(result.getString("password"));
                    receivedUser.setEmail(result.getString("email"));
                    receivedUser.setClub(result.getString("club"));
                    receivedUser.setPresident(result.getInt("is_president"));
                }
                
                
                
                if(user.getUserName().equals(receivedUser.getUserName()) && user.getPassword().equals(receivedUser.getPassword())){
                     
                    
                    System.out.println("Logged");
                    User.LoggedUSER.setUserName(receivedUser.getUserName());
                    User.LoggedUSER.setPassword(receivedUser.getPassword());
                    User.LoggedUSER.setEmail(receivedUser.getEmail());
                    User.LoggedUSER.setClub(receivedUser.getClub());
                    User.LoggedUSER.setPresident(receivedUser.getPresident());
                    System.out.println(User.LoggedUSER.getUserName() + " " + User.LoggedUSER.getEmail() + " " + User.LoggedUSER.getPassword() + " " + User.LoggedUSER.getPresident());
                    
                    
                    setVisible(false);
                    //dispose();
                    Chat_Selection chatSelection = new Chat_Selection();
                    chatSelection.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "User Name or Password is wrong!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                conn.close();
                
            } catch (ClassNotFoundException e) {
                System.out.println("Class not found");
            } catch ( SQLException e){
                System.out.println("SQL Exception");
            } catch (Exception e){
                System.err.println("Unknown Host");
            } 
            
        }
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void lblCreateNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateNewAccountMouseClicked
        setVisible(false);
        dispose();
        Creating_Account creatingAccount = new Creating_Account();
        creatingAccount.setVisible(true);
    }//GEN-LAST:event_lblCreateNewAccountMouseClicked

    private void TFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFieldPasswordFocusGained
        TFieldPassword.setText(null);
    }//GEN-LAST:event_TFieldPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JTextField TFieldName;
    private javax.swing.JPasswordField TFieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCreateNewAccount;
    // End of variables declaration//GEN-END:variables
}
